apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30000 # you can choose any port in the range 30000-32767

